# Exported from Render on 2025-10-30T06:14:51Z
version: "1"
services:
- type: web
  name: telegram-gaming-bot
  runtime: python
  repo: https://github.com/Johmid/telegram-gaming-bot
  plan: free
  envVars:
  - key: BOT_TOKEN
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python channel_bot.py
  healthCheckPath: /health
  autoDeployTrigger: commit
